name: Build Mod

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set Up Java
              uses: actions/setup-java@v5
              with:
                java-version: 8
                distribution: "temurin"

            - name: Build Jar
              run: ./gradlew build

            # TODO: THINK OF A BETTER WAY TO DO THISS
            - name: Prepare Artifact
              run: |
                rm -f build/libs/*-sources.jar

            - name: Upload Jar Artifact
              uses: actions/upload-artifact@v4
              with:
                name: Voicechat-1.10.2-Build-${{github.run_number}}
                path: build/libs/voicechat-*.jar